-- require('lspconfig')['pylsp'].setup {
--   before_init = function(params)
--     params.processId = vim.NIL
--   end,
--   cmd = {
--     'docker',
--     'run',
--     '-i',
--     '--name',
--     'pylsp-empto-backend',
--     '--rm',
--     '-v',
--     '/Users/viacheslav.litvinov/projects/empto/backend:/src',
--     'empto_backend:latest',
--     'pylsp'
--   }
-- }

